[db]
client          = "mysql"
conn_string     = "root:password@(127.0.0.1)/alertstrap?parseTime=true"
history_days    = 7
alerts_table    = "mon_alerts"
users_table     = "mon_users"

[ldap]
search_base     = "dc=example,dc=com"
host            = "ldap.example.com"
port            = 389
use_ssl         = false
bind_dn         = "%s"
bind_user       = ""
bind_pass       = ""
user_filter     = "(uid=%s)"
attributes      = { name="givenName", username="sAMAccountName", email="mail" }

[server]
listen          = ":8100"
cert_file       = ""
cert_key        = ""
alerts_limit    = 5000
alerts_resolve  = 300
alerts_delete   = 600
log_max_size    = 1
log_max_backups = 3
log_max_age     = 28
log_compress    = true
sync_nodes      = ["http://127.0.0.1:8000"]

[monit]
listen          = ":5000"

[[menu]]
id = "/kubernetes"
text = "Kubernetes"
class = "fa fa-th-large"

  [[menu.nodes]]
  id = "/kubernetes/prom"
  text = "prom"
  href = "/api/v1/alerts?match[]={job=\"prometheus\"}"

  [[menu.nodes]]
  id = "/kubernetes/test"
  text = "test"
  href = "/api/v1/alerts?match[]={job=\"prometheus\"}"

    [[menu.nodes.nodes]]
    id = "/kubernetes/test/test"
    text = "test"
    href = "/api/v1/alerts?match[]={job=\"prometheus\"}"

[[menu]]
id = "/kubernetes"
text = "Kubernetes"
class = "fa fa-gem"
 
  [[menu.nodes]]
  id = "/kubernetes/test_2"
  text = "test 2"
  href = "/api/v1/alerts?match[]={job=\"prometheus\"}"

  
