global:
  listen_address:   ":8100"
  cert_file:        ""
  cert_key:         ""
  alerts_limit:     10000
  alerts_resolve:   180
  alerts_delete:    600
  sync_nodes: 
    - "http://127.0.0.1:8000"
  
  db:
    client:         "mysql"
    conn_string:    "root:password@(127.0.0.1)/alertstrap?parseTime=true"
    history_days:   7
    alerts_table:   "mon_alerts"
    users_table:    "mon_users"

  ldap:
    search_base:    "dc=example,dc=com"
    host:           "localhost"
    port:           389
    use_ssl:        false
    bind_dn:        "%s"
    bind_user:      ""
    bind_pass:      ""
    user_filter:    "(uid=%s)"
    attributes:     
      name:         "givenName"
      username:     "sAMAccountName"
      email:        "mail" 

  monit:
    listen_address: ":5000"

menu:
  - id: "sdiscovery"
    text: "Service Discovery"
    class: "fa fa-th-list"

    nodes:
      - id: "alpha"
        text: "alpha"

      - id: "beta"
        text: "beta"

  - id: "kubernetes"
    text: "Kubernetes"
    class: "fa fa-th-large"

    nodes:
      - id: "alpha"
        text: "alpha"

      - id: "beta"
        text: "beta"

  - id: "monitoring"
    text: "Monitoring"
    class: "fa fa-chart-area"

    nodes:
      - id: "test"
        text: "Test Zones"

        nodes:
          - id: "alpha"
            text: "alpha"

          - id: "beta"
            text: "beta"

  - id: "alerttrap"
    text: "Alerttrap"
    class: "fa fa-chart-area"

    nodes:
      - id: "history"
        text: "History"

      

  - id: "netmap"
    text: "Netmap"
    class: "fa fa-cloud"

    nodes:
      - id: "alpha"
        text: "alpha"

      - id: "beta"
        text: "beta"

  - id: "vmetrics"
    text: "Victoria Metrics"
    class: "fa fa-chart-bar"

    nodes:
      - id: "test"
        text: "Victoria Metrics TEST"

        nodes:
          - id: "targets"
            text: "Targets"

          - id: "alerts"
            text: "Alerts"

      - id: "k8s"
        text: "Victoria Metrics K8S"

        nodes:
          - id: "targets"
            text: "Targets"

          - id: "alerts"
            text: "Alerts" 

  - id: "settings"
    text: "Settings"
    class: "fa fa-cogs"


  - id: "users"
    text: "Users"
    class: "fa fa-user"

    nodes:
      - id: "alpha"
        text: "alpha"

      - id: "beta"
        text: "beta"

