[mysql]
conn_string  = "root@(127.0.0.1)/showcase?multiStatements=true"
alerts_table = "messages.mon_alerts"
alerts_view  = "messages.mon_v_alerts"
hosts_view   = "showcase.mon_v_hosts"

[alertstrap]
listen_port  = ":8100"
login        = ""
passwd       = ""
location     = "Asia/Shanghai"
